name: Deploy Backend to EC2 via CodeDeploy

on:
  push:
    paths:
      - 'backend/**'
    branches: [ main ]

jobs:
  backend-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build JAR
      run: ./gradlew build
      working-directory: backend

    - name: Package app
      run: |
        mkdir -p deploy
        cp -r backend/build/libs deploy/
        cp backend/appspec.yml deploy/
        cp -r backend/scripts deploy/
        cd deploy && zip -r app.zip .

    - name: Upload to S3
      run: |
        aws s3 cp deploy/app.zip s3://${{ secrets.S3_BUCKET }}/backend/app.zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ap-northeast-2

    - name: Trigger CodeDeploy
      run: |
        aws deploy create-deployment \
          --application-name my-app \
          --deployment-group-name my-deploy-group \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --s3-location bucket=${{ secrets.S3_BUCKET }},bundleType=zip,key=backend/app.zip \
          --region ap-northeast-2
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ap-northeast-2
